# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


default: &default
  HELLO: developers
  S3_BUCKET_NAME: 'daydash-development'
  AWS_ACCESS_KEY_ID: 'AKIAJ3CURNBFIHWRY2WQ'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_REGION: 'ap-southeast-1'
  MAILGUN_USERNAME: 'postmaster@daydash.co'
  MAILGUN_PASSWORD: 'f6b0bf49107aedd15e63c574402fc595'
  MAILGUN_API_KEY: 'key-1eba6c459b82d4ef064a4ae1692fc333'

development:
  <<: *default
  HELLO: developers
  S3_BUCKET_NAME: 'daydash-development'

production:
  <<: *default
  HELLO: users
  S3_BUCKET_NAME: 'daydash'

  SECRET_KEY_BASE: "630e224e6202ec1d1756ef4318dd216cc1fe1f700f06ffd1fd1168d926d909167e40f1e3c25b97e8aadff8f54910d830ecbb8946b8382792f23450b4298064d3"
  DATABASE_PASSWORD:

# brick:
#   <<: *default
#   HELLO: users
#   S3_BUCKET_NAME: 'daydash'
#
#   SECRET_KEY_BASE: "630e224e6202ec1d1756ef4318dd216cc1fe1f700f06ffd1fd1168d926d909167e40f1e3c25b97e8aadff8f54910d830ecbb8946b8382792f23450b4298064d3"
#   DATABASE_PASSWORD:
#   MANDRILL_USERNAME: ""
#   MANDRILL_API_KEY:

test:
  <<: *default
  HELLO: rspec
  S3_BUCKET_NAME: 'daydash-test'
