
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Daydash_development

test:
  <<: *default
  database: Daydash_test

production:
  <<: *default
  # database: Daydash_production
  # username: Daydash
  # password: <%= ENV['DAYDASH_DATABASE_PASSWORD'] %>
  url: "postgres://deploy:Arnon007@localhost/daydash"
