
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Daydash_development

test:
  <<: *default
  database: Daydash_test

production:
  <<: *default
  database: daydash_production
  username: daydash
  password: <%= ENV['DAYDASH_DATABASE_PASSWORD'] %>
