
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wadealike_development

test:
  <<: *default
  database: wadealike_test

server: &server
  adapter: postgresql
  encoding: unicode
  database: wadealike_production
  username: wadealike
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

alpha:
  <<: *server
production:
  <<: *server
