
notification:
  cron: "*/5 * * * *"
  class: "NotificationJob"
  queue: default
  active_job: true

ReminderEvent:
  cron: "0 6 * * *"
  class: "ReminderJob"
  queue: default
  active_job: true

event_uptime:
  cron: "0 6 * * *"
  class: "EventJob"
  queue: default
  active_job: true
